<<<<<<< HEAD
# Generated by Django 2.1.5 on 2019-02-14 11:34
=======
# Generated by Django 2.1.5 on 2019-02-09 14:07
>>>>>>> 2182f3a4b8fdddf73aa0b260257e2d329ad6c815

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
